import type {Metadata} from "next";
import "./globals.css";
import {Header} from "@/components/Header/Header";
import styles from "./layout.module.css"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
          <div className={styles.wrapper}>
              <Header/>
              <div className={styles.body}>
                  {children}
              </div>
          </div>
      </body>
    </html>
  );
}
